name: Typecheck

on:
    push:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: setup
              run: |
                  npm install
            - name: typecheck
              run: npm run typecheck
